### ISSUE TITLE
Onefetch languages checklist

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/gengo#34]
>[!NOTE]
>I've been pinging a lot of onefetch contributors for help with languages I'm unfamiliar with. *If anyone finds this annoying, please let me know.* :slightly_smiling_face:

This is the list of languages supported by [onefetch][onefetch], as of when this issue was created. This tool should support most of these in order to replace tokei.

- [x] Abap
- [x] ABNF
- [x] Ada
- [x] Assembly
- [x] AutoHotKey
- [x] ~~Bash~~ This will be Shell
- [x] C
- [x] Ceylon
- [x] Clojure
- [x] CMake
- [x] CoffeeScript
- [x] ColdFusion
- [x] Coq
- [x] Cpp
- [x] Crystal
- [x] CSharp
- [x] Css
- [x] D
- [x] Dart
- [x] Dockerfile
- [x] Elisp
- [x] Elixir
- [x] Elm
- [x] Emojicode
- [x] Erlang
- [x] Fish
- [x] Forth (https://github.com/o2sh/onefetch/pull/35)
- [x] FortranLegacy
- [x] FortranModern
- [x] FSharp
- [x] GdScript
- [x] Glsl (https://github.com/o2sh/onefetch/pull/824)
- [x] Go
- [x] Graphql
- [x] Groovy
- [x] Haskell
- [x] Haxe (https://github.com/o2sh/onefetch/pull/394)
- [x] Hcl (https://github.com/o2sh/onefetch/pull/438)
- [x] Hlsl (https://github.com/o2sh/onefetch/pull/1082)
- [x] HolyC
- [x] Html
- [x] Idris (https://github.com/o2sh/onefetch/pull/54)
- [x] Java
- [x] JavaScript
- [x] Json
- [x] Jsonnet
- [x] Jsx (*NOTE:* Like linguist, this will probably be combined with JavaScript)
- [x] Julia
- [x] Jupyter
- [x] Kotlin
- [x] Lisp (Common Lisp)
- [x] LLVM (https://github.com/o2sh/onefetch/pull/507)
- [x] Lua
- [x] Makefile
- [x] Markdown
- [x] Nim
- [x] Nix
- [x] Objective C (https://github.com/o2sh/onefetch/pull/49)
- [x] OCaml
- [x] Odin
- [x] Org (https://github.com/o2sh/onefetch/pull/155)
- [x] Pascal (https://github.com/o2sh/onefetch/pull/989)
- [x] Perl
- [x] ~~Perl6~~ Raku (https://github.com/o2sh/onefetch/pull/303)
- [x] Php
- [x] PowerShell
- [x] Processing (https://github.com/o2sh/onefetch/pull/326)
- [x] Prolog (https://github.com/o2sh/onefetch/pull/94)
- [x] ~~Protobuf~~ Protocol Buffers
- [x] PureScript
- [x] Python
- [x] Qml (https://github.com/o2sh/onefetch/pull/362)
- [x] R
- [x] Racket (https://github.com/o2sh/onefetch/pull/124)
- [x] Renpy
- [x] Ruby
- [x] Rust
- [x] Sass
- [x] Scala
- [x] Scheme
- [x] Sh (Shell)
- [x] Solidity
- [x] Sql
- [x] Svelte
- [x] Swift
- [x] SystemVerilog (https://github.com/o2sh/onefetch/pull/797)
- [x] Tcl (https://github.com/o2sh/onefetch/pull/66)
- [x] Tex (https://github.com/o2sh/onefetch/pull/92 and https://github.com/o2sh/onefetch/pull/247)
- [x] Toml
- [x] Tsx (See note on JSX)
- [x] TypeScript
- [x] Vala (https://github.com/o2sh/onefetch/pull/324)
- [x] Verilog (https://github.com/o2sh/onefetch/pull/789)
- [x] Vhdl (https://github.com/o2sh/onefetch/pull/632)
- [x] VimScript
- [x] VisualBasic (https://github.com/o2sh/onefetch/pull/867)
- [x] Vue
- [x] WebAssembly (https://github.com/o2sh/onefetch/pull/495)
- [x] Wolfram (https://github.com/o2sh/onefetch/pull/609)
- [x] Xaml (https://github.com/o2sh/onefetch/commit/05fec5af40ecc223591ff344f03b4b6e87252aef)
- [x] Xml
- [x] XSL (https://github.com/o2sh/onefetch/pull/798)
- [x] Yaml
- [x] Zig
- [x] ~~Zsh~~ This will be Shell

Made with:

```ruby
#!/usr/bin/env ruby
require 'yaml'

filepath = ARGV[0]

langs = YAML.load_file(filepath)

langs.keys.each do |lang|
  puts "- [ ] #{lang}"
end
```

```shell
script.rb path/to/onefetch/languages.yaml
```

******

# Languages added later

- [x] Arduino (https://github.com/o2sh/onefetch/pull/1176)
- [ ] Modelica (https://github.com/o2sh/onefetch/pull/1262)
- [x] Agda (https://github.com/o2sh/onefetch/pull/1216)
- [x] Twig (https://github.com/o2sh/onefetch/pull/1257) (reverted with https://github.com/o2sh/onefetch/commit/324f3dfd2ed93710e18ea21f6d3c746c95d58859)
- [ ] V (https://github.com/o2sh/onefetch/pull/1252)
- [ ] CUDA (https://github.com/o2sh/onefetch/pull/940)
- [x] ATS (https://github.com/o2sh/onefetch/pull/523)
- [x] Oz (https://github.com/o2sh/onefetch/pull/1280)
- [x] SVG (https://github.com/o2sh/onefetch/pull/1266)
- [x] Astro (https://github.com/o2sh/onefetch/pull/1317)

[onefetch]: https://github.com/o2sh/onefetch

**Comment by spenserblack** [comment]
Related: #22

**Comment by spenserblack** [comment]
@atluft Pinging you since you made https://github.com/o2sh/onefetch/pull/789

I'm completely unfamiliar with Verilog. Would you be willing to make a PR to add support? If/when onefetch switches to this, then onefetch will be able to detect `*.v` as verilog :wink:

**Comment by spenserblack** [comment]
@o2sh, @jake-87 pinging you guys since you added support for fortran modern and fortran legacy. Not familiar with Fortran at all. Is there a reason that onefetch separated Fortran into modern and legacy besides the fact that that's what tokei did? Is the difference between the two significant enough to be considered different languages?
Also, I'm noticing that some of the [extensions tokei uses for modern](https://github.com/XAMPPRocky/tokei/blob/ae77e1945631fd9457f7d455f2f0f2f889356f58/languages.json#L497) are mapped to [`Fortran Free Form` in linguist](https://github.com/github-linguist/linguist/blob/916bd8f3df802fa98b0ea85539e67bd0b88ef158/lib/linguist/languages.yml#L2032-L2040).

**Comment by jake-87** [comment]
@spenserblack To make a long story short (and off the top of my head, mostly), they were implemented as different things mostly because they're really quite different languages - you can't take legacy fortran code and make it compile in modern fortran without quite a few changes, and vice-versa (The syntax may initially *look* similar, but there's many differences in how you structure it and what restrictions are placed on the programmer). If they're easy to tell apart (and they are, because they use different file extensions), then it makes more sense to consider them as seperate languages.

As for whether "Fortran Free Form" would be a better name, you could consider it as such, although I'd personally expect "Legacy FORTRAN" to be "Fortran fixed form", which seems confusing, so maybe "Legacy" and "Modern" are better names.

**Comment by spenserblack** [comment]
@jake-87 Thanks for the info!

**Comment by spenserblack** [comment]
Hi @alessandroasm! I'm pinging you because you've previously contributed to onefetch to support LLVM. We're considering [changing our language detection tool](https://github.com/o2sh/onefetch/pull/1152). If you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @spsandwichman! I'm pinging you because you've previously contributed to onefetch to support Odin. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @jephthai! I'm pinging you because you've previously contributed to onefetch to support Forth. We're considering https://github.com/o2sh/onefetch/pull/1152. Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @LordMZTE! I'm pinging you because you've previously contributed to onefetch to support Haxe. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @PsypherPunk! I'm pinging you because you've previously contributed to onefetch to support HCL. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @HallerPatrick! I'm pinging you because you've previously contributed to onefetch to support ProtoBuf. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

Or maybe I should ping @0rax? No worries if you don't know any Rust: I'm just pinging people that are likely familiar with the language to expedite getting Gengo into Onefetch and finally resolving https://github.com/o2sh/onefetch/issues/26.

**Comment by spenserblack** [comment]
Hi @rcon56! I'm pinging you because you've previously contributed to onefetch to support Wolfram. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @wigust! I'm pinging you because you've previously contributed to onefetch to support Scheme. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Hi @progDes007! I'm pinging you because you've previously contributed to onefetch to support HLSL. We're considering [changing our language detection tool to gengo](https://github.com/o2sh/onefetch/pull/1152). Gengo needs a bit more language support, so, if you're interested, we'd love your help!

**Comment by spenserblack** [comment]
Checking tokei, yes, it seems that `Lisp` is `Common Lisp`: https://github.com/XAMPPRocky/tokei/pull/717. Thanks for pointing that out!

**Comment by mdrakib651923** [comment]
### ****

**Comment by mdrakib651923** [comment]
****
